spring:
  redis:
    host: 127.0.0.1
    port: 6379
  application:
    name: tx-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tx-manager?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
server:
  port: 9111

tx-lcn:
  manager:
    host: 127.0.0.1
    port: 8070
    admin-key: 123456
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
logging:
  level:
    com.codingapi.txlcn: debug


